# Pane Styling
set -g pane-border-format " #[fg=blue]#[fg=black,bg=blue,bold] #P #[bg=default,fg=blue,nobold] "
set -g pane-active-border-style fg=blue
set -g pane-border-style fg=brightblack

# Window Status
set -g window-status-current-format "#[fg=magenta]#[fg=black,bg=magenta,bold]#I:#W#[bg=default,fg=magenta,nobold]"

# Status Right (System Info)
set -g status-right "#{?#($HOME/.tmux_scripts/tmux-spotify-info),#[fg=#1DB954]#[bg=#1DB954]#[fg=black]#($HOME/.tmux_scripts/tmux-spotify-info)#[bg=default]#[fg=#1DB954] ,}#[fg=blue]#[bg=blue]#[fg=black]󰥔 %H:%M#[bg=default]#[fg=blue] #[fg=cyan]#[bg=cyan]#[fg=black]󰃭 %Y-%m-%d#[bg=default]#[fg=cyan]"
