set -g pane-border-format " #[fg=cyan]#[fg=white,bg=cyan,bold] #P #[bg=default,fg=cyan,nobold] "
set -g pane-active-border-style fg=cyan
set -g pane-border-style fg=brightwhite
set -g window-status-current-format "#[fg=cyan]#[fg=white,bg=cyan,bold]#I:#W#[bg=default,fg=cyan,nobold]"
