add_newline = false
format = """
[╭─](bold blue) $directory$git_branch$git_status$git_state
[╰─](bold blue) $character
"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold yellow)"

[directory]
style = "bold cyan"
read_only = " 󰌾"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
format = '$all_status$ahead_behind '
ahead = '[⬆](bold purple) '
behind = '[⬇](bold purple) '
staged = '[✚](green) '
deleted = '[✖](red) '
renamed = '[➜](purple) '
stashed = '[✭](cyan) '
untracked = '[◼](white) '
modified = '[✱](blue) '
conflicted = '[═](yellow) '
diverged = '⇕ '
up_to_date = ''

[golang]
symbol = " "

[nodejs]
symbol = " "

[rust]
symbol = " "
